sudo: required
dist: trusty
language: python
notifications:
  email: false

python:
  #- "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

os:
  - linux
before_install:
  - ls /usr/lib/at-spi-core

install:
  - sudo pip install pywinauto
