sudo: required
dist: trusty
language: cpp

os:
  - linux
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-xenial
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit57-dev qtdeclarative57-dev qt57base
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
    
script:
  - qmake -qt=qt57 -v
  - qmake -qt=qt57
  - make
  - ./application
